version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorldNodeJsApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3lqqxlc2agul"
s3_prefix = "HelloWorldNodeJsApp"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
